version: '3.9'
services:   
    # Nginx Service 1    

    web_1: 

        build: 
            dockerfile: ./nginx/web1/Dockerfile
            context: ./nginx/web1
        image: nginx:latest
        container_name: web_1
        ports:
            - "8181:80"
        networks: 
            - ha-network 
        volumes:
            - ./nginx/web1/www/:/var/www/html
            - ./nginx/web1/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/web1/logs:/var/logs/nginx/
        
    web_2: 

        build: 
            dockerfile: ./nginx/web2/Dockerfile
            context: ./nginx/web2
        image: nginx:latest
        container_name: web_2
        ports:
            - "8182:80"
        networks: 
            - ha-network 
        volumes:
            - ./nginx/web2/www/:/var/www/html
            - ./nginx/web2/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/web2/logs:/var/logs/nginx/

    ha: 
    
        build: 
            dockerfile: ./haproxy/Dockerfile
            context: ./haproxy
        image: haproxytech/haproxy-ubuntu:latest 
        volumes:
            - ./haproxy:/haproxy-override
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        depends_on:
             - web_1
             - web_2
        ports:
             - "80:80"
        networks: 
            - ha-network                            

networks: 
    ha-network:
        driver: bridge